### PR TITLE
media-gfx/freecad: Fix opencascade dependency

### PR DESCRIPTION
**Pull request by robert7k**
freecad-0.18.4 does not build with opencascade-7.3.0

### CODE REVIEW

**Comment by waebbl** [comment]
Do you have a log file for the fail ready? I'm currently trying to reproduce this. Thanks!

**Comment by robert7k** [comment]
Unfortunately I don't have the logs anymore, but this is the error message I got:
`FAILED: lib/libSMDS.so`

**Comment by waebbl** [comment]
IIRC it's one of the internal smesh libraries.

**Comment by waebbl** [comment]
@robert7k I was able to reproduce the bug. It's not related to opencascade-7.4.0! FreeCAD builds fine with opencascade-7.3.0. I was able to build 0.18.4-r1 with 7.3.0 and currently are building the live ebuild to verify it works too, before pushing the changes.

The bug is rather related to a change I introduced when updating from 7.3.0 to 7.4.0 which changes the library install path of opencascade, so freecad doesn't find the opencascade libraries when linking.

I'm going to add a patch with PR #196 and crediting you there.

Thanks a lot for bringing this to my attention!

**Pull request closed without merging**
