### PR TITLE
media-gfx/freecad: fix boost placeholders problem

### PR DESCRIPTION
**Pull request by vowstar**
Closes: https://github.com/waebbl/waebbl-gentoo/issues/250
Package-Manager: Portage-3.0.5, Repoman-3.0.1
Signed-off-by: Huang Rui <vowstar@gmail.com>

### CODE REVIEW

**Comment by waebbl** [comment]
@vowstar Thanks for the contribution. Do you know whether the patch works for <boost-1.74.0 as well? So far, I wasn't able to build either boost-1.73.0 or boost-1.74.0 on my machine.

**Comment by vowstar** [comment]
> @vowstar Thanks for the contribution. Do you know whether the patch works for <boost-1.74.0 as well? So far, I wasn't able to build either boost-1.73.0 or boost-1.74.0 on my machine.

My boost version
*  dev-libs/boost
      Latest version available: 1.74.0
      Latest version installed: 1.74.0

It works on my machine, but this bug is very strange.

**Comment by waebbl** [comment]
Finally I was able to build boost-1.74.0.
Thanks for the contribution. The patch doesn't apply for me and failed for different line endings. I try to re-create the patch and apply it and see if it works.

**Comment by vowstar** [comment]
Thank you

**Comment by waebbl** [comment]
Has been solved with #253, so closing this.
I don't know what has caused the issue with different line endings. The two files looked identical :(
Thanks for your work on this!

**Pull request closed without merging**
